// Copyright (c) 2026 Amr Elsagaei. All rights reserved.

package recipe

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/amrelsagaei/updock/internal/project"
	"github.com/amrelsagaei/updock/internal/prompt"
	"github.com/amrelsagaei/updock/internal/security"
)

// CollectValues runs recipe prompts and collects all variable values.
func CollectValues(r *Recipe, autoGenerate bool) (map[string]string, error) {
	values := make(map[string]string)

	for _, p := range r.Prompts {
		if p.Generate == "password" && autoGenerate {
			pw, err := security.GeneratePassword()
			if err != nil {
				return nil, fmt.Errorf("generating %s: %w", p.Name, err)
			}
			values[p.Name] = pw
			continue
		}

		if p.Required && p.Default == "" {
			title := fmt.Sprintf("%s (required)", p.Name)
			if p.Description != "" {
				title = fmt.Sprintf("%s - %s (required)", p.Name, p.Description)
			}
			val, err := prompt.InputFunc(title, "", "")
			if err != nil {
				return nil, err
			}
			if val == "" {
				return nil, fmt.Errorf("%s is required", p.Name)
			}
			values[p.Name] = val
			continue
		}

		if p.Default != "" {
			values[p.Name] = p.Default
		}
	}

	return values, nil
}

// Render generates a docker-compose.yml and .env from a recipe and collected values.
// projectName is the on-disk project directory name, recorded in updock.json.
func Render(r *Recipe, values map[string]string, projectPath, projectName string) error {
	expand := func(key string) string {
		return values[key]
	}

	composeContent := buildRecipeCompose(r, expand)
	envContent := buildRecipeEnv(r, values)

	if err := os.WriteFile(filepath.Join(projectPath, "docker-compose.yml"), []byte(composeContent), 0o644); err != nil {
		return fmt.Errorf("writing compose: %w", err)
	}

	if err := os.WriteFile(filepath.Join(projectPath, ".env"), []byte(envContent), 0o600); err != nil {
		return fmt.Errorf("writing .env: %w", err)
	}
	_ = os.Chmod(filepath.Join(projectPath, ".env"), 0o600)

	gitignore := ".env\ndata/\n"
	if err := os.WriteFile(filepath.Join(projectPath, ".gitignore"), []byte(gitignore), 0o644); err != nil {
		return fmt.Errorf("writing .gitignore: %w", err)
	}

	cfg := recipeToConfig(r, values)
	if projectName != "" {
		cfg.ProjectName = projectName
	}
	meta := project.NewMetadata(cfg)
	if err := project.WriteMetadata(projectPath, &meta); err != nil {
		return fmt.Errorf("writing metadata: %w", err)
	}

	return nil
}

func buildRecipeCompose(r *Recipe, expand func(string) string) string {
	var b strings.Builder

	b.WriteString("# Generated by updock - yours to edit\n")
	b.WriteString("services:\n")

	for name := range r.Services {
		svc := r.Services[name]
		tag := svc.DefaultTag
		if tag == "" {
			tag = "latest"
		}
		fmt.Fprintf(&b, "  %s:\n", name)
		fmt.Fprintf(&b, "    image: %s:%s\n", svc.Image, tag)

		if len(svc.Ports) > 0 {
			b.WriteString("    ports:\n")
			for _, p := range svc.Ports {
				expanded := os.Expand(p, expand)
				fmt.Fprintf(&b, "      - \"%s\"\n", expanded)
			}
		}

		b.WriteString("    env_file:\n")
		b.WriteString("      - .env\n")

		if len(svc.Environment) > 0 {
			b.WriteString("    environment:\n")
			for k, v := range svc.Environment {
				expanded := os.Expand(v, expand)
				fmt.Fprintf(&b, "      %s: \"%s\"\n", k, expanded)
			}
		}

		if len(svc.DependsOn) > 0 {
			b.WriteString("    depends_on:\n")
			for _, dep := range svc.DependsOn {
				fmt.Fprintf(&b, "      - %s\n", dep)
			}
		}

		if len(svc.Volumes) > 0 {
			b.WriteString("    volumes:\n")
			for _, v := range svc.Volumes {
				fmt.Fprintf(&b, "      - %s\n", v)
			}
		}

		restart := svc.Restart
		if restart == "" {
			restart = "unless-stopped"
		}
		fmt.Fprintf(&b, "    restart: %s\n", restart)
	}

	if len(r.Volumes) > 0 {
		b.WriteString("\nvolumes:\n")
		for name := range r.Volumes {
			fmt.Fprintf(&b, "  %s: {}\n", name)
		}
	}

	return b.String()
}

func buildRecipeEnv(r *Recipe, values map[string]string) string {
	var b strings.Builder
	b.WriteString("# Generated by updock - edit freely\n")

	for _, p := range r.Prompts {
		if v, ok := values[p.Name]; ok {
			fmt.Fprintf(&b, "%s=%s\n", p.Name, v)
		}
	}

	return b.String()
}

func recipeToConfig(r *Recipe, values map[string]string) *project.Config {
	cfg := &project.Config{
		ProjectName: r.Meta.Name,
	}

	for svcName := range r.Services {
		svc := r.Services[svcName]
		if cfg.Image == "" {
			cfg.Image = svc.Image
			cfg.Tag = svc.DefaultTag
			if cfg.Tag == "" {
				cfg.Tag = "latest"
			}
		}
		for _, p := range svc.Ports {
			expanded := os.Expand(p, func(k string) string { return values[k] })
			if m, ok := parsePortMapping(expanded); ok {
				cfg.Ports = append(cfg.Ports, m)
			}
		}
	}

	for _, p := range r.Prompts {
		cfg.Env = append(cfg.Env, project.EnvVar{
			Key:      p.Name,
			Value:    values[p.Name],
			Secret:   p.Secret,
			Required: p.Required,
		})
	}

	return cfg
}

// parsePortMapping parses an expanded compose port string into a PortMapping.
// It accepts "host:container", "ip:host:container", and a trailing "/proto",
// and reports false when there is no published host port to record.
func parsePortMapping(s string) (project.PortMapping, bool) {
	parts := strings.Split(s, ":")
	if len(parts) < 2 {
		return project.PortMapping{}, false
	}
	hostStr := parts[len(parts)-2]
	containerStr := parts[len(parts)-1]
	if i := strings.IndexByte(containerStr, '/'); i >= 0 {
		containerStr = containerStr[:i]
	}
	host, err1 := strconv.Atoi(hostStr)
	container, err2 := strconv.Atoi(containerStr)
	if err1 != nil || err2 != nil {
		return project.PortMapping{}, false
	}
	return project.PortMapping{Host: host, Container: container}, true
}
