// Copyright (c) 2026 Amr Elsagaei. All rights reserved.

package scaffold

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/amrelsagaei/updock/internal/project"
)

// WriteComposeFile generates a docker-compose.yml for the project.
// Secrets are never inlined - they are referenced from .env.
func WriteComposeFile(projectPath string, cfg *project.Config) error {
	content := buildComposeContent(cfg)
	path := filepath.Join(projectPath, "docker-compose.yml")

	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("writing docker-compose.yml: %w", err)
	}
	return nil
}

func buildComposeContent(cfg *project.Config) string {
	var b strings.Builder

	b.WriteString("# Generated by updock - yours to edit\n")
	b.WriteString("services:\n")

	serviceName := project.DeriveProjectName(cfg.Image)
	fmt.Fprintf(&b, "  %s:\n", serviceName)
	fmt.Fprintf(&b, "    image: %s:%s\n", cfg.Image, cfg.Tag)

	if len(cfg.Ports) > 0 {
		b.WriteString("    ports:\n")
		for _, p := range cfg.Ports {
			hostVar := fmt.Sprintf("HOST_PORT_%d", p.Container)
			fmt.Fprintf(&b, "      - \"${%s:-%d}:%d\"\n", hostVar, p.Host, p.Container)
		}
	}

	b.WriteString("    env_file:\n")
	b.WriteString("      - .env\n")

	if len(cfg.Volumes) > 0 {
		b.WriteString("    volumes:\n")
		for _, v := range cfg.Volumes {
			fmt.Fprintf(&b, "      - ./%s:%s\n", v.HostPath, v.ContainerPath)
		}
	}

	b.WriteString("    restart: unless-stopped\n")

	return b.String()
}
