// Copyright (c) 2026 Amr Elsagaei. All rights reserved.

package scaffold

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/amrelsagaei/updock/internal/project"
)

// WriteEnvFile generates a .env file with 0600 permissions.
func WriteEnvFile(projectPath string, cfg *project.Config) error {
	content := buildEnvContent(cfg)
	path := filepath.Join(projectPath, ".env")

	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return fmt.Errorf("writing .env: %w", err)
	}

	if err := os.Chmod(path, 0o600); err != nil {
		return fmt.Errorf("setting .env permissions: %w", err)
	}

	return nil
}

func buildEnvContent(cfg *project.Config) string {
	var b strings.Builder

	b.WriteString("# Generated by updock - edit freely\n")

	for _, e := range cfg.Env {
		fmt.Fprintf(&b, "%s=%s\n", e.Key, e.Value)
	}

	for _, p := range cfg.Ports {
		fmt.Fprintf(&b, "HOST_PORT_%d=%d\n", p.Container, p.Host)
	}

	return b.String()
}

// WriteGitignore writes a .gitignore inside the project folder.
func WriteGitignore(projectPath string) error {
	content := ".env\ndata/\n"
	path := filepath.Join(projectPath, ".gitignore")

	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("writing .gitignore: %w", err)
	}
	return nil
}
